export const GET_CINEMAS_REQUEST = "GET_CINEMAS_REQUEST";
export const GET_CINEMAS_SUCCESS = "GET_CINEMAS_SUCCESS";
export const GET_CINEMAS_FAILURE = "GET_CINEMAS_FAILURE";

export const GET_CINEMAS_BY_ID_REQUEST = "GET_CINEMAS_BY_ID_REQUEST";
export const GET_CINEMAS_BY_ID_SUCCESS = "GET_CINEMAS_BY_ID_SUCCESS";
export const GET_CINEMAS_BY_ID_FAILURE = "GET_CINEMAS_BY_ID_FAILURE";