export const GET_MOVIES_SEARCH_REQUEST = "GET_MOVIES_SEARCH_REQUEST";
export const GET_MOVIES_SEARCH_SUCCESS = "GET_MOVIES_SEARCH_SUCCESS";
export const GET_MOVIES_SEARCH_FAILURE = "GET_MOVIES_SEARCH_FAILURE";
