// LAY DANH SACH LOAI NGUOI DUNG
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_REQUEST =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_REQUEST";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_SUCCESS =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_SUCCESS";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_FAILURE =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_FAILURE";
//LAY DANH SACH NGUOI DUNG PHAN TRANG
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_REQUEST =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_REQUEST";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_SUCCESS =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_SUCCESS";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_FAILURE =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_FAILURE";
// THAY DOI THONG TIN PHAN TRANG
export const THAY_DOI_THONG_TIN_PHAN_TRANG_NGUOI_DUNG =
  "THAY_DOI_THONG_TIN_PHAN_TRANG_NGUOI_DUNG";
