export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_REQUEST =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_REQUEST";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_SUCCESS =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_SUCCESS";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG_FAILURE =
  "LAY_DANH_SACH_LOAI_NGUOI_DUNG_FAILURE";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_REQUEST =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_REQUEST";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_SUCCESS =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_SUCCESS";
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_FAILURE =
  "LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG_FAILURE";
