export const LAY_DANH_SACH_PHONG_VE_REQUEST = "LAY_DANH_SACH_PHONG_VE_REQUEST"
export const LAY_DANH_SACH_PHONG_VE_SUCCESS = "LAY_DANH_SACH_PHONG_VE_SUCCESS"
export const LAY_DANH_SACH_PHONG_VE_FAILURE = "LAY_DANH_SACH_PHONG_VE_FAILURE"
export const DAT_GHE = "DAT_GHE"
