export const CHANGE_VALUE_SEARCH = "CHANGE_VALUE_SEARCH";
export const SEARCH_MOVIE_ID_REQUEST = "SEARCH_MOVIE_ID_REQUEST";
export const SEARCH_MOVIE_ID_SUCCESS = "SEARCH_MOVIE_ID_SUCCESS";
export const SEARCH_MOVIE_ID_FAILURE = "SEARCH_MOVIE_ID_FAILURE";
