import "bootstrap/dist/css/bootstrap.css";
import "./App.css";
import "react-modal-video/scss/modal-video.scss";
//My css
import "./home.scss"
import "./test.scss"
import "./login.scss"
import "./signUp.scss"
import "./index.css";
import "./index.scss";
