export const inputList = [
  {
    inputName: "maPhim",
    label: "Mã Phim",
    placeholder: "Mã Phim",
    deafaultValue: 0,
    type: "number",
    disabled: true,
  },
  {
    inputName: "tenPhim",
    label: "Tên Phim",
    placeholder: "Tên Phim",
    deafaultValue: "",
    type: "text",
    disabled: false,
  },
  // {
  //   inputName: "biDanh",
  //   label: "Bí Danh",
  //   placeholder: "Bí Danh",
  //   deafaultValue: "",
  //   type: "text",
  //   disabled: false,
  // },
  {
    inputName: "trailer",
    label: "Trailer",
    placeholder: "Trailer",
    deafaultValue: "",
    type: "text",
    disabled: false,
  },
  {
    inputName: "hinhAnh",
    label: "Hình Ảnh",
    placeholder: "Hình Ảnh",
    deafaultValue: undefined,
    type: "file",
    disabled: false,
  },
  {
    inputName: "moTa",
    label: "Mô Tả",
    placeholder: "Mô Tả",
    deafaultValue: "",
    type: "text",
    disabled: false,
  },
  {
    inputName: "maNhom",
    label: "Mã Nhóm",
    placeholder: "Mã Nhóm",
    deafaultValue: "GP13",
    type: "text",
    disabled: true,
  },
  {
    inputName: "ngayKhoiChieu",
    label: "Ngày Khởi Chiếu",
    placeholder: "Ngày Khởi Chiếu",
    deafaultValue: "",
    type: "text",
    disabled: false,
  },
  {
    inputName: "danhGia",
    label: "Đánh Giá",
    placeholder: "Đánh Giá",
    deafaultValue: 6,
    type: "number",
    disabled: false,
  },
];
